### ISSUE TITLE
재우야. 어떻게 실행해야 하는지 좀 등록해주라.

### ISSUE THREAD

**Issue by yongwoo2** [WooJaeWoo/PayItForward#21]

**Comment by WooJaeWoo** [comment]
아, 벌써 보셨군요ㅠㅠ 아직 좀 덜 했는데ㅠㅠㅠㅠ
아직 서버 공부하는 중이라서 서버 동작 시키시지 않으셔도 되구요,
HTML5_for_mixed라는 폴더에 good.html 위주로 봐주셨으면 해요~
근데 페이지 구성하느라 시간을 많이 써서 디데일한 애니메이션을 아직 못 넣었어요ㅠㅠ
